#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals  # unicode by default

from django.contrib.gis.db import models


class Update(models.Model):
    """An update generated by users interaction"""

    title = models.CharField(max_length=256, blank=False)
    user = models.CharField(max_length=256, blank=False)
    date = models.DateTimeField(auto_now=True)

    typ = models.CharField(max_length=32, blank=False, db_index=True)
    object_type = models.CharField(max_length=32, blank=False, db_index=True)

    # def __unicode__(self):
    #     return unicode(self.title)

    @property
    def name(self):
        return self.title
